### ISSUE TITLE
Youtube search doesn‘t work properly and throws an error

### ISSUE THREAD

**Issue by jclsn** [xbmc/Official-Kodi-Remote-iOS#98] opened 2020-08-01 15:46 UTC
You can not enter anything. If you tap on something from the search history it works, but it still throws an error

![image](https://user-images.githubusercontent.com/19779511/89105138-e4be3700-d41e-11ea-9372-bb4fba03c837.png)

**Comment by wutschel** [comment] 2021-01-26 06:46
Does it work on Kodi itself? Or are you also getting an error when using the Kodi UI?

**Comment by coldspark29** [comment] 2021-01-26 08:57
No just with the remote of course.

**Comment by wutschel** [comment] 2021-01-26 09:46
I am asking as I installed the YT Add-on yesterday, and I do see the same error on my remote. But at the same time there is an error popup in the Kodi UI which asks to register the YT Add-on. The same error I get when using the YT Add-on from the Kodi UI. Just wanted to check, if you possibly also did not register the Add-on yet.

**Comment by coldspark29** [comment] 2021-01-26 09:48
What do you mean by register? I made an API key and all. Else Youtube does not work on Kodi

**Comment by wutschel** [comment] 2021-01-26 09:50
> What do you mean by register? I made an API key and all. Else Youtube does not work on Kodi

Yes, that´s what I meant. So, works for you on Kodi UI and does not work with Remote.

**Comment by kambala-decapitator** [comment] 2022-04-19 06:50
FYI just received one more AppStore feedback about this, I think we should investigate

**Comment by wutschel** [comment] 2022-06-27 19:58
Finally I got the YouTube Add-On configured. The search works for me (example below searches for "genesis live").

https://abload.de/img/bildschirmfoto2022-064tjbe.png

But be aware, you need to enter the search via the YouTube menu. If you apply search via pulling down a list view, this will just search/filter within the items in the list itself.

**Comment by wutschel** [comment] 2022-07-08 13:59
@kambala-decapitator: 

> But be aware, you need to enter the search via the YouTube menu. If you apply search via pulling down a list view, this will just search/filter within the items in the list itself.

Is this possibly related to the reported problems?

**Comment by kambala-decapitator** [comment] 2022-07-09 07:17
> Is this possibly related to the reported problems?

might be, hard to say

**Comment by wutschel** [comment] 2022-07-09 07:23
I responded to the user in the AppStore. Let's see.

**Comment by jclsn** [comment] 2022-07-09 07:26
I didn't write something in the app store. I also don't use the addon anymore.

**Comment by wutschel** [comment] 2022-07-09 07:29
> I didn't write something in the app store. I also don't use the addon anymore.

Hi, thanks for still following this. In case you might start using the add-on again, just let us know if it works as described above. Sorry for the late response from my side, but I simply wasn't using the add-on before and the registration was a bit cumbersome. The response in AppStore was given to a 2nd user who also reported problems with searching in the YT add-on.

**Comment by wutschel** [comment] 2023-04-09 15:42
@kambala-decapitator, I propose t close this one as solved. The search definitely works.

**Closed** 2023-04-09 15:48 UTC

**Comment by wutschel** [comment] 2024-02-11 10:51
Now it is understood and reproducible, see https://github.com/xbmc/Official-Kodi-Remote-iOS/issues/986.
