### ISSUE TITLE
Order by date of recordings in the TV sections when using pvr-hts

### ISSUE THREAD

**Issue by nkichukov** [xbmc/Official-Kodi-Remote-iOS#134] opened 2021-01-18 14:08 UTC
Ordering by date of the video recordings under the pvr-hts TV section (Kodi Matrix) (tvheadend backend) does not work properly.

**Comment by wutschel** [comment] 2021-01-19 06:51
Can you give a few more details on what is the expected and the observed behaviour? Which version of the Kodi Remote App do you use (AppStore´s 1.5.7, 1.6 test builds, own build)? Is this also seen with older versions of Kodi?

**Comment by nkichukov** [comment] 2021-01-19 12:22
AppStore's 1.5.7
Kodi Matrix (I cannot test on another builds as I have none at this moment)

If you navigate the recordings in kodi and set ordering by date, the recordings in kodi order properly, say 'most recent' on top.
If you open TV section and go to 'Recordings', then the recordings are not displayed as per kodi's setting 'most recent' on top, they just fall under some random order.

Does this help reproduce?

**Comment by wutschel** [comment] 2021-01-19 12:48
Thanks, can you install the latest App version from TestFlight? You can get the test build from there: [forum thread](https://forum.kodi.tv/showthread.php?tid=359717).
And, just to make sure: You did set the sorting for date in the App as well?
I will try to look into this, but I have no PVR function enabled on my Kodi setup (until now).

**Comment by nkichukov** [comment] 2021-01-25 11:55
The test app does not install on my iOS device, after I click on install from testflight, the button appears to be installing, but in the end it becomes 'Install' again. So I cannot test with 1.6.

I am unable to find sort in the iOS app under the Recordings. I can just change icons or list view. Where did you change the sort order for the TV section?

**Comment by wutschel** [comment] 2021-01-25 12:39
> The test app does not install on my iOS device,

Hmm, what device and iOS do you use?

> Where did you change the sort order for the TV section?

I didn´t sort at all as my setup has no PVR support. Was just asking, if you did. Now I understood this is not even possible.

When looking at the code -- at least at a first glance -- I cannot see sort a command being configured for PVR. But without the ability to test this I cannot work on it. So, someone else needs to take this up.

**Comment by nkichukov** [comment] 2021-01-25 14:22
the phone runs ios 14.3.

Lacking option to sort in the ios app made me believe it 'inherits' the sort order of kodi, however, it does not, perhaps you can check out the link between configured kodi sort (which works fine) and the actual sort of the ios app?

If you at least can make the ios app honour kodi's configured sorting, then I can test this out (if I can install it from testflight).

**Comment by wutschel** [comment] 2021-01-25 16:08
With an iPhone and iOS 14.3 the App should be installable. Did you remove/deinstall the App (v1.5.7) which you installed via AppStore before trying to install the one from TestFlight?

**Comment by nkichukov** [comment] 2021-01-25 16:14
No, I will try to remove it first and share results. Thanks

**Comment by nkichukov** [comment] 2021-01-25 16:26
It worked, however now it fails to list anything with:

PVR.GetRecording failure. I shared the feedback and will be rolling the stable version now.

**Comment by wutschel** [comment] 2021-01-25 16:57
Thanks for testing and sharing your feedback. Let´s who can take this up.

**Comment by wutschel** [comment] 2021-01-26 06:45
I took a deeper look into it and it seems the API (I checked v12 on [this page](https://kodi.wiki/view/JSON-RPC_API/v12#List.Limits)) does not support sorting for PVR functions at all. Without the API supporting "sort" this cannot be implemented into the Remote App.

**Comment by nkichukov** [comment] 2021-01-26 10:29
Right, we do not need to have the sorting functionality in the iOS app, we can just display what we received from kodi.

Kodi sorts the recordings properly, starting from most recent recording on top.

If we can get the app not to modify this sorting, then this will be the solution I am looking for. Can we do that?

**Comment by wutschel** [comment] 2021-01-26 10:34
No, without any sort option in the API I see no way to do this.

**Comment by wutschel** [comment] 2021-01-26 11:41
And the list sorting in Yatse follows the sorting you do in the Kodi UI?

**Comment by nkichukov** [comment] 2021-01-27 11:14
Changing the sort order in kodi, does not seem to affect yatse, so they must sort internally, based on a sane default:
Date / descending (oldest first)

**Comment by wutschel** [comment] 2021-01-27 17:44
Yes, sounds like in yatse sorting was implemented independent of the API.

**Comment by nkichukov** [comment] 2021-01-28 11:34
yes, can we have something similar, ideally provide the option to select sort method in the app, but if not, then at least default to something more handy by default?

**Comment by wutschel** [comment] 2021-01-29 07:00
Personally I would not implement sorting into the Remote App. I clearly prefer to use the API logic. Would be better if you can raise a Feature Request for Kodi itself.

**Comment by nkichukov** [comment] 2021-01-29 19:15
What exactly do you need changed in the API in kodi so I can document it there?

**Comment by wutschel** [comment] 2021-01-30 13:52
On https://kodi.wiki/view/JSON-RPC_API/v12 you can see how it should look like. You can see in all `PVR.Get`-functions -- in your case `PVR.GetRecordings` -- that there is no support for 
```
{
"$ref": "List.Sort",
"name": "sort"
},
```
like it is available for many other API command like `AudioLibrary.GetArtists`. Hope this helps.

**Comment by nkichukov** [comment] 2021-02-08 09:55
The latest release (1.6) broke any PVR listing with the bug I have already provided while testflight-testing the release.

Do we need patched kodi with https://github.com/xbmc/xbmc/pull/19177 to have the new version not fail to list any recordings and recover the previous state?

And the second question: with the upstream change to the json-rpc API can we have the ios app obey the sort order from kodi?

**Comment by wutschel** [comment] 2021-02-08 11:01
There was no change done yet. It still should work (as buggy) like before, and it does for me (tested with version 1.6 from AppStore and a local build from master). Please make sure you are doing a clean install.

**Comment by nkichukov** [comment] 2021-02-08 11:08
PVR recordings listing works no more, I have reported this problem during testflight stage, so you should be able to access the screenshot with the failure too. This is a breaking change for me.

List-sorting in the remote app is not available, so there are no such options, see history of this bug report.

**Comment by wutschel** [comment] 2021-02-08 11:18
Sorry, but I need to be able to reproduce this, and here it works. I do not have access to the screen shots you shared, maybe @kambala-decapitator can share them.

Of course list sorting is not available. It can only be added, when the sort option is available via Kodi API. Now, as this has been submitted, I will wait until it is in a nightly build and then work on adding this to the App.

**Comment by kambala-decapitator** [comment] 2021-02-08 11:27
I guess that's it:

<img src="https://user-images.githubusercontent.com/1557784/107213222-26a4e700-6a19-11eb-868b-f661538965c8.jpg" width="50%" >

**Comment by nkichukov** [comment] 2021-02-08 11:36
yes, that's the one.

In case that matters the kodi addon version for tvheadend installed is: pvr.hts v7.1.4 on Kodi (19.0-ALPHA1 (18.9.701) Git:20200903-b9fecf9a9c-dirty).

**Comment by wutschel** [comment] 2021-02-08 11:37
Hmm, the ERROR message ("The data ...") must come from Kodi and not from the Remote App. This is the `methodError` coming from the JSON response. Maybe someone from the Kodi team can give a hint on what can cause this.

**Comment by howie-f** [comment] 2021-02-08 14:21
No problems here with Version 1.6 `PVR.GetRecordings` - tested with v18 and also current v19 (once with #19177 applied, once without).

Then i wanted to try your version, @nkichukov but commit `b9fecf9a9c` doesn't exist in history. also `-dirty` implies there are other changes in the build you're using, that probably cause this error.

in short: i can't reproduce it either, all good here

**Comment by nkichukov** [comment] 2021-02-08 15:54
Hi, it does have the dirty as it is a fork for raspberrypi install that adds HEVC hardware acceleration. This should not relate to the json-rpc as this part of the code comes directly from upstream.

I have compiled the latest RC1: Kodi (19.0-RC1 (18.9.910) Git:20210208-e9557255a5-dirty) and installed pvr.hts v8.2.2 (latest from master) and it still fails to list the recordings.

@howie-f what's your PVR backend? Is it tvheadend?

**Comment by howie-f** [comment] 2021-02-08 16:05
yup, tvh 4.2.8-37~gabce894dc, kodi 19.0-RC1, pvr.hts 8.2.2, no problems, sorry

**Comment by nkichukov** [comment] 2021-02-09 20:36
Same here, do you happen to have any recordings in the list?

**Comment by howie-f** [comment] 2021-02-10 10:07
yes i get my 28 recordings retrieved.
_this is definitely not an issue of Official Kodi Remote_.
may try to request `{"jsonrpc":"2.0","method":"PVR.GetRecordings","id":1,"params":{"properties":["title"]}}` via CURL. this responds with `{"id":1,"jsonrpc":"2.0","result":{"limits":{"end":28,"start":0,"total":28},"recordings":.....(full list here)` at my end.

**Comment by nkichukov** [comment] 2021-02-10 18:30
This works fine:

```
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Type: application/json
Content-Length: 29522
Cache-Control: private, max-age=0, no-cache
Accept-Ranges: none
Date: Wed, 10 Feb 2021 18:28:38 GMT

{"id":1,"jsonrpc":"2.0","result":{"limits":{"end":239,"start":0,"total":239},"recordings":[{...cut...
```

Are you using authentication to hit the json rpc api?

**Comment by howie-f** [comment] 2021-02-10 18:55
@nkichukov enabled web-server in kodi on 8080, credentials set..
allow remote control from this system / .... from other systems: both enabled
and here is the config of my remote:
![IMG_3816](https://user-images.githubusercontent.com/58829855/107557127-80540f80-6bd9-11eb-8a34-c3ca47d2012e.PNG)

now if that still doesn't work for you, **please let's open a forum thread** to stop annoying the other parties here :)
maybe it's a valid bug but we never ran into it... or maybe like it should be

**Comment by wutschel** [comment] 2021-02-11 07:15
Good news. With the latest Kodi nightly build (a976d2f) and a few -- still kind of hacky -- changes the Kodi Remote App can sort recordings:

<a href="https://abload.de/image.php?img=simulatorscreenshot-inxjhr.png"><img src="https://abload.de/img/simulatorscreenshot-inxjhr.png" /></a> <a href="https://abload.de/image.php?img=simulatorscreenshot-irpk4n.png"><img src="https://abload.de/img/simulatorscreenshot-irpk4n.png" /></a>

Few questions:
1. Is there a way to really sort by "date"? I can only get it working when sorting by "starttime" as seen on the picture left.
2. sort options are reasonable? For now I would go for title, channel, starttime, runtime.

The code needs some more work as I need to find a good way to make the sort request depending on the Kodi version. Currently this is all hardcoded -- following the Kodi Remote standard way of configuring JSON commands.

**Comment by nkichukov** [comment] 2021-02-11 09:30
Hi, do you mean you have kodi that includes:
https://github.com/xbmc/xbmc/pull/19177/commits/c055479095f948371bc4eac68c9c291a5c8cb471 ?

Mine already has it, so I could test your changes(well, I cannot right now due to the other failure that was introduced with 1.6 release) if you testflight publish them.

Sorting by: 'title, channel, starttime, runtime' makes perfect sense and I think it covers what I need (starttime - new recordings on top).
Thanks

**Comment by howie-f** [comment] 2021-02-11 09:46
nice, regarding the json-rpc version:

request ======> `{"jsonrpc":"2.0","method":"JSONRPC.Version","id":1}`
response <==== `{"id":1,"jsonrpc":"2.0","result":{"version":{"major":12,"minor":2,"patch":0}}}` (that is 12.2.0 for the nightly). could be the app is already requesting the version somewhere, otherwise this needs to be added, maybe after connect.

the new sort option can only be used with version `>= 12.1.0` and a think the gui elements need to be hidden with lower versions, too. the app should just look like it is now for older json-rpc versions.

the sort order: kodi gui offers four options for recordings (with pvr.hts):
- Date _desc_ (the default): => `"params":{"properties":[...],"sort":{"order":"descending","method":"date"}}`
- Name _asc_ => `"sort":{"order":"ascending","method":"label"}` method is **label**
- Duration _asc_ => `"sort":{"order":"ascending","method":"time"}` method is **time**
- FIle _asc_ (doesnt make sense to me, but would add it also for completeness)
  => `"sort":{"order":"ascending","method":""file}` method is **file**

**starttime** returns an error, though that field is named like this internally:
=> `"params":{"properties":["title"],"sort":{"order":"descending","method":"starttime"}`
<= `{"message":"Received value does not match any of the defined enum values"..`

looks like there needs to be some kinda translation in the app, i.e. 'Duration' -> 'time'.... etc.

**Comment by wutschel** [comment] 2021-02-11 11:52
Hmm, this sounds not too promising. I really get no sorted results when asking to sort for `"date"`, only `"starttime"` works. Is this depending on the Add-on used? I am using kodi-pvr-vuplus.

I can test the method `"time"`, in the current implementation `"runtime"` is used.

UI and translations I am not worried about yet. :) But I will be. The App´s implementation uses an quite huge compile time configuration in `AppDelegate.m` for the UI elements' names/functions/visibility and also the JSON methods, parameters, options and such. So, adding the new stuff for either all or no server versions is easy, adapting this at runtime will need some work ... I am not sure how to do this yet.

**Comment by howie-f** [comment] 2021-02-11 12:28
> Is this depending on the Add-on used?

should not be, because sorting is done in kodi after retrieving the unordered list from the backend.
`starttime` as well as `runtime` are both not defined in the schema, kodi doesn't have knowledge about those identifiers for `List.Sort`: https://github.com/xbmc/xbmc/blob/4a937d9cd1731b547914bf6f8abed3c7e392b5d6/xbmc/interfaces/json-rpc/schema/types.json#L104-L113

so what you could do now is maybe enable debug-logging and json-rpc logging.
then `tail -f kodi.log | grep JSONRPC`, and then retrieve a starttime-sorted recordings list by the app.
the json received by kodi would look something like this:
```
DEBUG <general>: JSONRPC: Incoming request: 
   {"method":"PVR.GetRecordings","id":649426891,"jsonrpc":"2.0","params":{"properties":
   ["title","starttime","endtime","plot","plotoutline","genre","playcount","resume",
   "channel","runtime","lifetime","icon","art","streamurl","file","directory"]}}
```
in theory you'll see the sort option there which must be `"method":"date"` even though the app is querying `starttime`
can you reproduce this? i think then the first step is done towards the goal :)

when i'm posting requests and responses here i'm always sending by terminal `curl -X POST -H "content-type:application/json" http://kodi:kodi@192.168.200.105:8080/jsonrpc -d '{...}'`. because zero knowledge of objective c or how the app internally works.

**Comment by howie-f** [comment] 2021-02-11 12:40
well now i see there‘s starttime and runtime in that json above 😳
but anyway, the sort method must be date for starttime, and time for runtime.... ugly, hmm

**Comment by howie-f** [comment] 2021-02-11 13:52
@wutschel if it turns out (i really cannot know) what you started implementing does the sorting by the app itself, then.. FWIW..
keep going this path. would be way less complicated. no need to check the json-rpc version, no need to hide controls, and it's working for any kodi version. which is a big +1. okay, now that sort-option has been introduced, but it doesn't hurt though.
my 2 cents on this ;)

**Comment by wutschel** [comment] 2021-02-11 17:29
I can assure you that I didn´t implement any sorting, and I won´t. I just added a configuration (hardly 10 lines of code) for the PVR-functions which then triggers to add the UI elements and sends the "sort" command. Also, I cannot see any occurance of "date" in the whole codebase. Really strange. I will read through your advice to check what commands finally reach Kodi server.
If you´re interested I can just push this and you can take a look at what is sent as well. The code changes are really simple to change and play around with.

**Comment by howie-f** [comment] 2021-02-11 17:37
yes very interested :) if you don‘t want to pr please point me to your branch

**Comment by wutschel** [comment] 2021-02-11 17:40
Here we go: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/pvrget_sort

**Comment by howie-f** [comment] 2021-02-11 21:41
@wutschel 2 commits for you to look at https://github.com/howie-f/Official-Kodi-Remote-iOS/commits/master
maybe they could help, i played a little with the remote

**Comment by nkichukov** [comment] 2021-02-16 16:49
Sorting on 12.1 does not work for me, I am going to upgrade to 12.2 and check on there.

Thanks for the fix, when do we expect to have this released in the appstore/testflight?

**Comment by wutschel** [comment] 2021-02-16 17:16
The code which implements this feature is not merged yet, and will not be merged into the next release as well. Please be patient.

**Comment by nkichukov** [comment] 2021-02-17 16:42
I see, you ended up implementing the sorting inside the app, thus making it kodi version independent, but anyhows added the 'sort' method for those versions that support it.

What I tried to say was that kodi json rpc api sorting does not work, just attempted on 12.2.1 and still nothing that changes the json response. I do not test it in the app, I run curl calls, like this:

```
{"jsonrpc":"2.0","method":"PVR.GetRecordings","id":1,"params":{"properties":["title","starttime"]},"sort":{"order":"descending","method":"starttime"}}
```
or
```
{"jsonrpc":"2.0","method":"PVR.GetRecordings","id":1,"params":{"properties":["title","starttime"]},"sort":{"order":"ascending","method":"starttime"}}
```
Even if I try to sort by 'recordingid' there is no change in the response. Thus PVR Kodi JSON RPC sort does not work, even though 'sort' is now available method. Again, this is different than this report, I just misunderstood that kodi json rpc api was successfully doing the sorting for you.

Thanks again, looking forward to testing the in-app sorting feature.

**Comment by howie-f** [comment] 2021-02-17 16:52
you need to use `"sort":{"order":"descending","method":"date"}` as`starttime` isn't defined in json-api

List.Sort: https://github.com/xbmc/xbmc/blob/4a937d9cd1731b547914bf6f8abed3c7e392b5d6/xbmc/interfaces/json-rpc/schema/types.json#L104-L113

**Comment by nkichukov** [comment] 2021-02-17 19:51
I've tried that as well, no matter what I tried it always returns the list in the same order.
`
{"id":1,"jsonrpc":"2.0","result":{"version":{"major":12,"minor":2,"patch":1}}}
`
here.

Do you see a different behaviour?

**Comment by howie-f** [comment] 2021-02-17 20:08
yes with `{"id":1,"jsonrpc":"2.0","result":{"version":{"major":12,"minor":2,"patch":1}}}`

```
{"jsonrpc":"2.0","method":"PVR.GetRecordings","id":1,
 "params":{"properties":["title"],"sort":{"order":"descending","method":"date"}}}
```
retrieves _latest_ recording **first**

```
{"jsonrpc":"2.0","method":"PVR.GetRecordings","id":1,
 "params":{"properties":["title"],"sort":{"order":"ascending","method":"date"}}}
```
retrieves _latest_ recording **last**

**Comment by nkichukov** [comment] 2021-02-17 21:04
Thanks @howie-f , seems like I had a typo which was closing the "params" field and did not include "sort" in there.
Confirmed, it works.

When do we get to test the new changes in the app?

**Comment by kambala-decapitator** [comment] 2021-02-19 20:51
this will be testable in Testflight v1.6.2 which will be available in 12 hours or so (as soon as it's reviewed and approved by Apple)

**Comment by wutschel** [comment] 2021-02-21 08:23
> When do we get to test the new changes in the app?

TestFlight version is up (1.6.2 Build 2068): Follow this [forum post](https://forum.kodi.tv/showthread.php?tid=359717&pid=3015228#pid3015228).

**Comment by nkichukov** [comment] 2021-02-21 11:30
Perfect, it works! 

Finally, a feature that was long ago missed and is now not dependent on the kodi json rpc api version too.

Well done, folks! Great work. This can be closed.

**Closed** 2021-02-21 20:20 UTC
