### ISSUE TITLE
Review localised date formats

### ISSUE THREAD

**Issue by kambala-decapitator** [xbmc/Official-Kodi-Remote-iOS#442] opened 2021-10-30 10:49 UTC
In #440 we discovered that some date format strings are in localised resources and one Chinese format is already broken: https://github.com/xbmc/Official-Kodi-Remote-iOS/blob/master/XBMC%20Remote/zh-Hans.lproj/Localizable.strings#L153

I suggest to remove format strings from localisation entirely as well as `LocaleIdentifier` key. App already knows which localisation it's running in and OS should take care of proper dates localisation based on the current locale and system settings.

Also consider using standard short and long styles, see `-[NSDateFormatter setDateStyle]`.

**Comment by wutschel** [comment] 2021-10-31 13:59
I added a first PR to handle the `setDateStyle`-part. 

As a work in progress I also replaced the `LocaleIdentifier` strings with `currentLocale` on a local branch. But this has unwanted side effects: When you select a certain Remote App language this does not reflect in the date formatting (e.g. "May, 27, 2006" for English or "27. Mai 2006" for German), the date formatting sticks to the system's regional setting.

**Comment by kambala-decapitator** [comment] 2021-10-31 14:05
> When you select a certain Remote App language this does not reflect in the date formatting (e.g. "May, 27, 2006" for English or "27. Mai 2006" for German), the date formatting sticks to the system's regional setting.

there's a trick how to force app to think that the selected language is the same as in system settings, related to `AppleLanguages` defaults key iirc.

Although I'm not even sure that it's a good idea to have an in-app language switch: iOS already has a concept of preferred languages.

**Comment by wutschel** [comment] 2021-10-31 21:56
I am personally fine to remove the in-app language switch. Question is, if user may miss this once they got used to this feature.

**Comment by wutschel** [comment] 2021-11-01 11:56
It seems user will not really lose the App language switching. Current situation is that switching the preferred language  via iOS is ignored, and only the Remote App language is used. When changing the code to replace the `LocaleIdentifier` strings and all related settings, the preferred language does work as intended. The locale is not derived from the selected language anymore, but still from the system settings. This is really how it should work, imho.

<a href="https://abload.de/image.php?img=bildschirmfoto2021-118gjjw.png"><img src="https://abload.de/img/bildschirmfoto2021-118gjjw.png" /></a>

In fact, there are currently even inconsistencies in the use of locale. Some time/date strings are using `currentLocale`, but most make use the localized strings. One more "+" for changing this. Shall I add the code to the open PR?

**Comment by wutschel** [comment] 2021-11-01 11:56
It seems user will not really lose the App language switching. Current situation is that switching the preferred language  via iOS is ignored, and only the Remote App language is used. When changing the code to replace the `LocaleIdentifier` strings and all related settings, the preferred language does work as intended. The locale is not derived from the selected language anymore, but still from the system settings. This is really how it should work, imho.

<a href="https://abload.de/image.php?img=bildschirmfoto2021-118gjjw.png"><img src="https://abload.de/img/bildschirmfoto2021-118gjjw.png" /></a>

In fact, there are currently even inconsistencies in the use of locale. Some time/date strings are using `currentLocale`, but most make use the localized strings. One more "+" for changing this. Shall I add the code to the open PR?

**Comment by kambala-decapitator** [comment] 2021-11-01 12:58
> Shall I add the code to the open PR?

sounds like a dedicated PR to me

**Comment by wutschel** [comment] 2021-11-01 13:00
> sounds like a dedicated PR to me

Fine for me. I will raise the new PR once #449 was merged.

**Closed** 2021-11-04 13:41 UTC
