### ISSUE TITLE
Stream audio/video/pictures to remote

### ISSUE THREAD

**Issue by avibrazil** [xbmc/Official-Kodi-Remote-iOS#860] opened 2023-03-09 02:35 UTC
Please make the remote to be able to also play on iOS device the Kodi server’s content.

thank you in advance

**Comment by kambala-decapitator** [comment] 2023-03-09 05:19
you'd rather just install Kodi on iOS and use a shared Kodi DB. out of the box iOS can't handle all file types that Kodi can and adding custom handlers is really out of scope for the remote.

also duplicate of #702

**Closed by kambala-decapitator** 2023-03-09 05:19 UTC
