### ISSUE TITLE
Remote missing on swipe left

### ISSUE THREAD

**Issue by heitbaum** [xbmc/Official-Kodi-Remote-iOS#672] opened 2022-04-26 10:44 UTC
Hi team. Go to movies. Choose a movie. Click play. It goes to the “now playing screen within movies”, swipe left (and the remote is missing)

First 2 are not working

![image](https://user-images.githubusercontent.com/6086324/165282837-16629b46-a6af-47cd-817a-9ccb97f68ca0.png)
![image](https://user-images.githubusercontent.com/6086324/165282857-ecea112f-cf74-45aa-8a34-18def591fef1.png)

Second 2 are working (go via now watching)

![image](https://user-images.githubusercontent.com/6086324/165283057-8f2ecd1b-bdc4-4797-99e7-ec0d56c9a982.png)
![image](https://user-images.githubusercontent.com/6086324/165283070-4b925592-9db8-4c37-aaab-ab67bc8b8d41.png)

Here is the test flight version.

![image](https://user-images.githubusercontent.com/6086324/165283133-2dcd82b9-01ed-4636-8617-88ff14c92058.png)

**Comment by kambala-decapitator** [comment] 2022-04-26 10:45
does it work in appstore version?

**Comment by heitbaum** [comment] 2022-04-26 10:49
> does it work in appstore version?

Yes. Was working fine ~ (till yesterday I think.)

**Comment by wutschel** [comment] 2022-04-26 18:47
Hmm, this might become difficult. Just tested the TF version on my iPhone (running iOS 15.4.1) which is connected to Kodi 19.4. In the cases you describe I always see the remote after a swipe left. Same test result when building current master with Xcode 13.2.1 and running on iOS 14.5 and 15.2 simulator.
@heitbaum: Is it possible to double check with an older Kodi version, e.g. 19.4?

**Comment by heitbaum** [comment] 2022-04-27 11:51
My phone is an iPhone 12 Pro - 15.5 19F5057e // most of my devices are running a nexus release of some sort at the moment. I’ll put LE10.0.2 on one on the weekend.

I have put Test Flight 1.10 (3288) back on my phone. And did a quick check - all seems ok. Whereas using 1.11 (3326) five minutes before I saw the error.

I just tried with one of the other iPhone 12 Pro 15.4.1 (with 1.11) it had the error. First movie - remote displayed. Second one did not (as below)

I’ll run 1.10 on mine for a couple of days and see that I don’t get the bug. And will try 1.10.1 on the other iPhone.

![E2310379-19A2-4085-A10E-0887EBF48002](https://user-images.githubusercontent.com/6086324/165511917-35783084-d347-4650-88cb-efd6e650e190.png)

**Comment by wutschel** [comment] 2022-04-27 12:59
> I just tried with one of the other iPhone 12 Pro 15.4.1 (with 1.11) it had the error. First movie - remote displayed. Second one did not (as below)

Just to understand this right, when you first movie works, second does not. Does this mean you face a kind of random error, or does it mean the error always happens on the 2nd movie in the list and it always works on the first? One more question: How exactly do you start the movie? Via selecting "Play" from the long press menu (from the list of movies) or via the play icon on the navigation bar in the movie details?

**Comment by wutschel** [comment] 2022-04-27 19:59
> Does this mean you face a kind of random error, or does it mean the error always happens on the 2nd movie in the list and it always works on the first? One more question: How exactly do you start the movie? Via selecting "Play" from the long press menu (from the list of movies) or via the play icon on the navigation bar in the movie details?

I could now reproduce it. This happens also with Kodi 19.4, Xcode 13.2.1 and an iOS 15.2 simulator, it does not happen on iOS 14.5 though. The code change which seems to fix it is this one: https://github.com/wutschel/Official-Kodi-Remote-iOS/tree/fix_content_view

@kambala-decapitator, you have an idea what changed and if the App is somehow calling this in a wrong way?

**Comment by kambala-decapitator** [comment] 2022-04-28 11:42
@wutschel wasn't aware of such behavior/change.

the whole method and cell creation/setup reserve refactoring :)

**Comment by heitbaum** [comment] 2022-04-28 11:59
I did more testing tonight. 

Click the > via movies and it “errors” on 1.11. 
Hold down via movies and choose play works.

1.10 - 3288 works fine.
Testing 1.10.1 - 3317 now.

**Comment by wutschel** [comment] 2022-04-28 12:10
> @wutschel wasn't aware of such behavior/change.
> 
> 
> 
> the whole method and cell creation/setup reserve refactoring :)

I am sure it does. :)
Would be great if you can help with pointing me to the right way of doing this. There are several controllers which do this in a somehow similar way. While brief testing I saw no problem in iOS 15.x though.

**Comment by heitbaum** [comment] 2022-04-30 06:33
Final results from testing. I could only reproduce this using this with 1.11 (3326) and ios 15.x. Error still occurs with the latest 15.5 (19F5062g) beta this week.

**Comment by wutschel** [comment] 2022-04-30 17:35
Thanks for the testing. This sounds like effects caused by moving to Xcode 13 SDK. Overall now 4 issues were found (2 already fixed with the first 1.11 build), now 2 more ones. Seems t was a good idea to not include any other change for the first 1.11 build -- triaging would have been more difficult.

**Closed** 2022-05-20 13:18 UTC

**Comment by heitbaum** [comment] 2022-05-24 09:47
@wutschel - can confirm working correctly on 15.5 and 15.6

**Comment by wutschel** [comment] 2022-05-25 04:14
Great, thanks for confirming!
